# Generated by Django 3.0.1 on 2020-01-01 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='image',
            field=models.ImageField(default='', upload_to='dj/images'),
        ),
    ]
